apiVersion: eventing.knative.dev/v1beta2
kind: EventType
metadata:
  name: dev.knative.info.request
spec:
  reference:
    apiVersion: serving.knative.dev/v1
    kind: Service
    name: knative-text-responder
  description: "This answers any and all questions you have about Knative"
  schemaData: '{"query":{"type":"string","description":"The query you would like to ask about Knative"}}' 
  type: "dev.knative.info.request"
