apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: chat-app
rules:
  - apiGroups:
      - "eventing.knative.dev"
    resources:
      - eventtypes
    verbs:
      - get
      - watch
      - list
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: chat-app-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: chat-app-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: chat-app
subjects:
  - kind: ServiceAccount
    name: chat-app-sa
    namespace: default

